import { describe, expect, it } from "vitest";
import { checkOriginality, findTells, longestShared, overlap, shingles, OVERLAP_REVIEW } from "./originality";

/**
 * The case asks the quality gate for "plagiarism / AI-detection checks". These tests pin
 * what the module claims and, just as importantly, what it refuses to claim: it reports
 * measured overlap and quoted phrases, never a verdict on authorship.
 */

const UK = "Vitamin C serum brightens skin and protects against daily damage. Apply it in the morning before sunscreen. A concentration between ten and twenty percent suits most skin types.";
const TRANSLATED = "Vitamin C serum brightens skin and protects against daily damage. Apply it in the morning before sunscreen. Swedish buyers search a compound noun instead.";
const INDEPENDENT = "Danish shoppers split the compound. Local pharmacies stock three formats and the pricing differs sharply from the rest of the region.";

describe("shingles and overlap", () => {
  it("builds 8-word sequences and finds none in text too short to have one", () => {
    expect(shingles("one two three").size).toBe(0);
    expect(shingles("a b c d e f g h i").size).toBe(2);
  });

  it("scores a near-duplicate high and an independent draft low", () => {
    expect(overlap(UK, TRANSLATED)).toBeGreaterThan(OVERLAP_REVIEW);
    expect(overlap(UK, INDEPENDENT)).toBe(0);
  });

  it("is 1 against itself and 0 against nothing", () => {
    expect(overlap(UK, UK)).toBe(1);
    expect(overlap("", UK)).toBe(0);
    expect(overlap(UK, "")).toBe(0);
  });

  it("quotes the longest shared run so a human can judge it rather than a score", () => {
    const shared = longestShared(UK, TRANSLATED);
    expect(shared).toContain("brightens skin and protects against daily damage");
    expect(longestShared(UK, INDEPENDENT).split(" ").length).toBeLessThan(3);
  });
});

describe("unedited-output phrases", () => {
  it("counts each phrase and returns the sentence it sits in", () => {
    const tells = findTells("In today's world, skincare matters. It's important to note that vitamin C oxidises. In conclusion, store it dark.");
    expect(tells.map((t) => t.phrase)).toEqual(expect.arrayContaining(["in today's world", "it is important to note".replace("it is", "it's"), "in conclusion"]));
    expect(tells[0].examples[0]).toContain("skincare matters");
  });

  it("finds nothing in prose that carries none of them", () => {
    expect(findTells(INDEPENDENT)).toEqual([]);
  });
});

describe("checkOriginality across a market set", () => {
  const reports = checkOriginality([
    { market: "UK", text: UK },
    { market: "SE", text: TRANSLATED },
    { market: "DK", text: INDEPENDENT },
  ]);

  it("returns one report per market", () => {
    expect(reports.map((r) => r.market)).toEqual(["UK", "SE", "DK"]);
  });

  it("flags the pair that is one page published twice, and says which pair", () => {
    const se = reports.find((r) => r.market === "SE")!;
    expect(se.needsReview).toBe(true);
    expect(se.overlaps[0].against).toBe("UK draft");
    expect(se.reasons.join(" ")).toMatch(/one page published twice/);
  });

  it("leaves an independently written market alone", () => {
    const dk = reports.find((r) => r.market === "DK")!;
    expect(dk.worstOverlap).toBe(0);
    expect(dk.needsReview).toBe(false);
    expect(dk.reasons).toEqual([]);
  });

  it("never returns a verdict on authorship, only counted evidence", () => {
    for (const r of reports) {
      // every reason is traceable to a number or a quoted phrase, never "written by AI"
      expect(r.reasons.join(" ")).not.toMatch(/written by|generated by|is AI/i);
      for (const o of r.overlaps) expect(o.ratio).toBeGreaterThanOrEqual(0);
    }
  });

  it("survives an empty draft set and an empty draft", () => {
    expect(checkOriginality([])).toEqual([]);
    const one = checkOriginality([{ market: "UK", text: "" }]);
    expect(one[0].words).toBe(0);
    expect(one[0].needsReview).toBe(false);
  });
});
